[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "gym-management"
version = "1.0.0"
description = "Gym Management System"
requires-python = ">=3.8"
dependencies = [
    "setuptools",
    "Flask",
    "pandas",
    "openpyxl",
    "gunicorn"
]
